language: python
python:
  - "3.6"
  - "3.7"
sudo: required
dist: xenial
install:
  - sudo apt-get update
  - pwd
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # - bash deps/travis_install.sh
  - conda install faiss-cpu=1.4.0 -c pytorch --use-local
  - pip install --ignore-installed -q -r test_requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 3.7 ]]; then pip install tensorflow; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl; fi
  - pip install -e .
  - python setup_nltk.py
  - python -m spacy download en
script:
  # - python -m unittest discover (no need to run twice)
  - coverage run -m unittest discover
cache: pip
cache:
  directories:
  - $HOME/.m2

after_success:
  - codecov --token=f0d32575-0b97-4e8b-bb76-26795958b4cc