import argparse
import time

def get_arg_parser():
    '''
    Create arg parse for training containing options for
        optimizer
        hyper parameters
        model saving
        log directories
    '''
    parser = argparse.ArgumentParser(description='Train Named Entity Recognition on Train Conll2003.')

    # Parser data loader options
    parser.add_argument('--load', action='store_true', help='load the saved files')
    parser.add_argument('--save', action='store_true', help='save the loaded data loaders')
    parser.add_argument('--clean', action='store_true', help='delete saved files')
    parser.add_argument('--train', action='store_true', help='train the network')
    parser.add_argument('--train_elmo_bi_lstm', action='store_true', help='train the ELMo BiLSTM CRF model')
    parser.add_argument('--train_bi_lstm', action='store_true', help='train the BiLSTM CRF model')
    parser.add_argument('--train_dictionary', action='store_true', help='train a dictionary classifier')
    parser.add_argument('--num_epochs', type=int, default=2, help='number of epochs to train on')
    parser.add_argument('--num_workers', type=int, default=2, help='number of workers for dataset')
    parser.add_argument('--shuffle', action='store_true', help='should shuffle the dataset for training')
    parser.add_argument('--batch_size', type=int, default=32, help='the batch size for specified training')
    parser.add_argument('--embedding_dim', type=int, default=300, help='embedding dimensions for the LSTM features')
    parser.add_argument('--hidden_dim', type=int, default=1000, help='hidden dimensions of LSTM outputs for feature size')
    parser.add_argument('--learning_rate', type=float, default=0.1, help='learning rate for optimizer')
    parser.add_argument('--weight_decay', type=float, default=1e-4, help='weight decay for weight update')
    parser.add_argument('--save_dir', type=str, default='saved_models/', help='directory for saved models')
    parser.add_argument('--model_name', type=str, default='model_{}'.format(time.time()), help='model_name')
    parser.add_argument('--log_dir', type=str, default='tensor_logs/', help='model_name')
    parser.add_argument('--model_path', type=str, help='the path for the saved model')

    parser.add_argument('--sample', type=float, default=1.0, help='the amount of training data to use 1.0 => 100% 0 => 0%')
    parser.add_argument('--dataset', type=str, default='CONLL', help='the supported datasets: SCIERC, CONLL')
    parser.add_argument('--cuda', action='store_true', help='enable cuda')
    parser.add_argument('--summary_file', default='summary.csv', type=str, help='name of the summary file being generated by the logger')
    parser.add_argument('--binary_classifier', default=None, type=str, help='if specified, will only classify a certain class')
    parser.add_argument('--training_threshold', default=100, type=int, help='The amount of samples to use to evaluate F1 score in training pipeline')
    parser.add_argument('--optimizer_type', default='SGD', type=str, help='The optimizer to use')
    parser.add_argument('--momentum', type=float, default=0.0, help='The momentum for SGD optimizer')

    return parser